import os
from dotenv import load_dotenv
from flask import Flask, redirect, render_template, request, flash, url_for 
import random

load_dotenv()

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "default_secret_key")

suggested_movies = []


#---------------------------
# Recommender logic and structure based on tutorials from:
# https://www.datacamp.com/tutorial/recommender-systems-python
#https://www.stratascratch.com/blog/step-by-step-guide-to-building-content-based-filtering
#https://realpython.com/build-recommendation-engine-collaborative-filtering/
#https://github.com/windowshopr/Weighted-Scoring-System-Repo

#----------------------
#FILM LIBRARY BUILD - Fields defined by dev and film samples generated by Claude AI
#----------------------

FILMS =[
    {
        "title": "Hot Fuzz",
        "genre": "Comedy",
        "mood": "laugh",
        "pace": "fast",
        "focus": "light",
        "runtime": "medium",
        "pick_type": "crowd",
        "year": 2007,
        "description": "A fast, funny action-comedy set in an absurdly dangerous English village.",
        "poster": "hot-fuzz.jpeg"
    },
    {
        "title": "Edge of Tomorrow",
        "genre": "Sci-Fi",
        "mood": "excited",
        "pace": "fast",
        "focus": "light",
        "runtime": "medium",
        "pick_type": "crowd",
        "year": 2014,
        "description": "A smart, entertaining sci-fi action film built around a time loop.",
        "poster": "edge-of-tomorrow.jpeg"
    },
    {
        "title": "Little Miss Sunshine",
        "genre": "Comedy",
        "mood": "laugh",
        "pace": "balanced",
        "focus": "light",
        "runtime": "medium",
        "pick_type": "crowd",
        "year": 2006,
        "description": "A warm, offbeat family comedy about failure, hope, and a disastrous road trip.",
        "poster": "little-miss-sunshine.jpeg"
    },
    {
        "title": "Zodiac",
        "genre": "Thriller",
        "mood": "thoughtful",
        "pace": "balanced",
        "focus": "layered",
        "runtime": "long",
        "pick_type": "critics",
        "year": 2007,
        "description": "A meticulous investigative thriller about obsession, uncertainty, and a killer who stays just out of reach.",
        "poster": "zodiac.jpeg"
    },
    {
        "title": "Before Sunrise",
        "genre": "Romance",
        "mood": "emotional",
        "pace": "slow",
        "focus": "focused",
        "runtime": "medium",
        "pick_type": "hidden",
        "year": 1995,
        "description": "A tender, talk-driven romance built around one night of connection between two strangers.",
        "poster": "before-sunrise.jpeg"
    },
    {
        "title": "Mad Max: Fury Road",
        "genre": "Action",
        "mood": "excited",
        "pace": "intense",
        "focus": "light",
        "runtime": "medium",
        "pick_type": "crowd",
        "year": 2015,
        "description": "A relentless action spectacle driven by survival, speed, and astonishing visual energy.",
        "poster": "mad-max-fury-road.jpeg"
    },
    {
        "title": "Lady Bird",
        "genre": "Drama",
        "mood": "emotional",
        "pace": "balanced",
        "focus": "focused",
        "runtime": "short",
        "pick_type": "critics",
        "year": 2017,
        "description": "A sharp, heartfelt coming-of-age film about identity, ambition, and difficult family love.",
        "poster": "lady-bird.jpeg"
    },
    {
        "title": "Moon",
        "genre": "Sci-Fi",
        "mood": "thoughtful",
        "pace": "slow",
        "focus": "layered",
        "runtime": "short",
        "pick_type": "hidden",
        "year": 2009,
        "description": "A quiet and intelligent science-fiction drama about isolation, identity, and human worth.",
        "poster": "moon.jpeg"
    },
    {
        "title": "Knives Out",
        "genre": "Mystery",
        "mood": "laugh",
        "pace": "fast",
        "focus": "focused",
        "runtime": "medium",
        "pick_type": "crowd",
        "year": 2019,
        "description": "A witty modern whodunit full of sharp dialogue, family dysfunction, and clever reversals.",
        "poster": "knives-out.jpeg"
    },
    {
        "title": "Drive",
        "genre": "Thriller",
        "mood": "thoughtful",
        "pace": "slow",
        "focus": "focused",
        "runtime": "medium",
        "pick_type": "hidden",
        "year": 2011,
        "description": "A stylish, moody crime thriller balancing tenderness, violence, and cool restraint.",
        "poster": "drive.jpeg"
    },
    {
        "title": "The Grand Budapest Hotel",
        "genre": "Comedy",
        "mood": "laugh",
        "pace": "fast",
        "focus": "layered",
        "runtime": "medium",
        "pick_type": "critics",
        "year": 2014,
        "description": "A playful, meticulously crafted comedy about loyalty, chaos, and a vanished old world.",
        "poster": "the-grand-budapest-hotel.jpeg"
    },
    {
        "title": "Prisoners",
        "genre": "Thriller",
        "mood": "emotional",
        "pace": "intense",
        "focus": "focused",
        "runtime": "long",
        "pick_type": "critics",
        "year": 2013,
        "description": "A dark, gripping thriller about desperation, morality, and the cost of taking justice personally.",
        "poster": "prisoners.jpeg"
    },
    {
        "title": "Booksmart",
        "genre": "Comedy",
        "mood": "laugh",
        "pace": "fast",
        "focus": "light",
        "runtime": "short",
        "pick_type": "crowd",
        "year": 2019,
        "description": "A lively, funny coming-of-age comedy about friendship, panic, and one last chaotic night.",
        "poster": "booksmart.jpeg"
    },
    {
        "title": "Her",
        "genre": "Romance",
        "mood": "thoughtful",
        "pace": "slow",
        "focus": "layered",
        "runtime": "medium",
        "pick_type": "critics",
        "year": 2013,
        "description": "A melancholy, intimate love story exploring technology, loneliness, and emotional connection.",
        "poster": "her.jpeg"
    },
    {
        "title": "The Nice Guys",
        "genre": "Comedy",
        "mood": "laugh",
        "pace": "fast",
        "focus": "light",
        "runtime": "medium",
        "pick_type": "hidden",
        "year": 2016,
        "description": "A breezy detective comedy with chaotic chemistry, ridiculous violence, and plenty of charm.",
        "poster": "the-nice-guys.jpeg"
    },
    {
        "title": "Nightcrawler",
        "genre": "Thriller",
        "mood": "excited",
        "pace": "intense",
        "focus": "layered",
        "runtime": "medium",
        "pick_type": "critics",
        "year": 2014,
        "description": "A tense, unsettling thriller about ambition, media voyeurism, and moral collapse.",
        "poster": "nightcrawler.jpeg"
    },
    {
        "title": "Once",
        "genre": "Romance",
        "mood": "emotional",
        "pace": "slow",
        "focus": "light",
        "runtime": "short",
        "pick_type": "hidden",
        "year": 2007,
        "description": "A small, sincere romance carried by music, longing, and beautifully understated emotion.",
        "poster": "once.jpeg"
    }
]


#----------------------
# QUIZ LABELS
#----------------------
#These labels convert short stored answer values
#into readable profile text for the results page
PROFILE_LABELS = {
    "mood" : {
        "laugh":"Looking for humour",
        "excited": "Looking for excitement",
        "emotional": "Open to emotional impact",
        "thoughtful": "In the mood for something thoughtful"
    },
    "pace" : {
        "slow":"Prefers a calm pace",
        "balanced": "Wants a balanced pace",
        "fast": "Wants something fast-moving",
        "intense": "Wants something intense"
    },
    "focus" : {
        "light":"Low-effort viewing",
        "medium": "Fairly light viewing",
        "focused": "Happy to concentrate",
        "layered": "Open to something layered"
    },
    "runtime" : {
        "short":"Shorter runtime preferred",
        "medium": "Standard runtime preferred",
        "long": "Longer runtime preferred",
        "any": "Runtime is not a big deal"
    },
    "pick_type" : {
        "crowd":"Leaning toward a crowd pleaser",
        "critics": "Leaning toward a critic's choice",
        "hidden": "Interested in a hidden gem",
        "surprise": "Open to anything"
    },

}

#----------------------
# Defining Scoring weights
#----------------------

WEIGHTS = {
    "mood": 3,
    "pace": 2,
    "focus": 2,
    "runtime": 2,
    "pick_type": 1
}
MAX_SCORE = sum(WEIGHTS.values())


#----------------------
# Python Logic functions
#----------------------

# Fetch answers from form 
def get_answers_from_form(form):
    return{
        "mood": form.get("mood", "").strip(),
        "pace": form.get("pace", "").strip(),
        "focus": form.get("focus", "").strip(),
        "runtime": form.get("runtime", "").strip(),
        "pick_type": form.get("pick_type", "").strip(),
    }

# Confirm answers before recommendation gen
def answers_are_complete(answers):
    return all(value for value in answers.values())

# creating profile from answers 
def build_user_profile(answers):
    profile = []

    for key, value in answers.items():
        label = PROFILE_LABELS.get(key, {}).get(value)
        if label:
            profile.append(label)

    return profile

# Answer score system build - compares a film's
#stored attribute against the user's answer.
#Weight points added for each match and collects
#short reason strings explaining the match

def score_standard_match(film, answers):
    score = 0
    reasons = []

    if film["mood"] == answers["mood"]:
        score += WEIGHTS["mood"] 
        reasons.append("matched your mood")

    if film["pace"] == answers["pace"]:
        score += WEIGHTS["pace"] 
        reasons.append("fit your preferred pace")
    
    if film["focus"] == answers["focus"]:
        score += WEIGHTS["focus"] 
        reasons.append("matched your level of attention tonight")

    if answers["runtime"] == "any":
        score += 1
        reasons.append("worked for a flexible runtime")
    elif film["runtime"] == answers["runtime"]:
        score += WEIGHTS["runtime"] 
        reasons.append("suited your available time")

    if answers["pick_type"] == "surprise":
        score += 1
        reasons.append("stated open to a wildcard pick")
    elif film["pick_type"] == answers["pick_type"]:
        score += WEIGHTS["pick_type"] 
        reasons.append("fit the kind of pick you wanted")

    return score, reasons

    

# Build for copy on results panels routing
def score_film(film, answers):
    score, reasons = score_standard_match(film, answers)

    film_copy = film.copy()
    film_copy["score"] = score
    film_copy["reasons"] = reasons



    film_copy["match_percent"] = round((film_copy["score"] / MAX_SCORE * 100))

    return film_copy

# Back up recommendations ranking build

def get_ranked_recommendations(answers, limit=4):
    scored_films = [score_film(film, answers) for film in FILMS]

    scored_films.sort(
        key=lambda item: (item["score"], item["year"]),
        reverse=True
    )

    return scored_films[:limit]

@app.route('/')
def home():
    return render_template('index.html', title="Home")


@app.route('/suggestions', methods=['GET', 'POST'])
def suggestions():
    if request.method == 'POST':
        title = request.form.get('title')
        genre = request.form.get('genre')
        reason = request.form.get('reason')

#Validation for suggestion form fields

        if not title or not genre or not reason:
            flash("Please fill in all fields.")
            return redirect(url_for('suggestions'))
        
        suggested_movies.append({
            'title': title,
            'genre': genre,
            'reason': reason
        })

        flash("Thank you for your suggestion!")
        return redirect(url_for('suggestions'))
    return render_template('suggestions.html', title="Suggest a Movie", suggested_movies=suggested_movies)  
    
@app.route('/about')
def about():
    return render_template('about.html', title="About")

@app.route('/random')
def random_movie():
#Return random film choice from the library
    random_film = random.choice(FILMS)
    return render_template(
    "random.html", 
    title="Take a Chance",
    random_film=random_film)

@app.route('/quiz')
def quiz():
    return render_template('quiz.html', title="Find a Film")


@app.route('/results', methods=["POST"])
def results():
    answers = get_answers_from_form(request.form)

    if not answers_are_complete(answers):
        flash("Please answer all five questions before continuing.")
        return render_template("quiz.html", title="Find a Film")
    
    recommendations = get_ranked_recommendations(answers, limit=4)
    top_pick = recommendations[0]
    backup_picks = recommendations[1:]
    user_profile = build_user_profile(answers)

    return render_template(
        'results.html', 
        title="Your Result",
        top_pick=top_pick,
        backup_picks=backup_picks,
        user_profile=user_profile,
        answers=answers
    )

if __name__ == "__main__":
    debug_flag = str(os.environ.get("DEBUG", "False")).lower() in ("1", "true", "yes")
    app.run(debug=debug_flag)
    


